### ISSUE TITLE
Make Terraform 0.12 compatible

### ISSUE THREAD

**Issue by meyskens** [src-d/lookout-terraform-analyzer#15]
Terraform 0.12 includes HCL2 with a radical different style, we should upgrade the analyzer to support it.

**Comment by meyskens** [comment]
PR: https://github.com/src-d/lookout-terraform-analyzer/pull/16
(Do not release till we switched to Terraform 0.12)

**Comment by rporres** [comment]
Looks good. Blocking a back to backlog until we move to 0.12

**Comment by meyskens** [comment]
We're moving, let's release this

**Comment by meyskens** [comment]
https://github.com/src-d/lookout-terraform-analyzer/releases/tag/v0.3.0
